#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pycollada
Version  : 0.7.2
Release  : 11
URL      : https://files.pythonhosted.org/packages/c1/7e/91cb2540947f0e8bcdee83e61a7b278784ac2d25f2864091344590a2619f/pycollada-0.7.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/c1/7e/91cb2540947f0e8bcdee83e61a7b278784ac2d25f2864091344590a2619f/pycollada-0.7.2.tar.gz
Summary  : python library for reading and writing collada documents
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-pycollada-license = %{version}-%{release}
Requires: pypi-pycollada-python = %{version}-%{release}
Requires: pypi-pycollada-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(python_dateutil)

%description
No detailed description available

%package license
Summary: license components for the pypi-pycollada package.
Group: Default

%description license
license components for the pypi-pycollada package.


%package python
Summary: python components for the pypi-pycollada package.
Group: Default
Requires: pypi-pycollada-python3 = %{version}-%{release}

%description python
python components for the pypi-pycollada package.


%package python3
Summary: python3 components for the pypi-pycollada package.
Group: Default
Requires: python3-core
Provides: pypi(pycollada)
Requires: pypi(numpy)
Requires: pypi(python_dateutil)

%description python3
python3 components for the pypi-pycollada package.


%prep
%setup -q -n pycollada-0.7.2
cd %{_builddir}/pycollada-0.7.2
pushd ..
cp -a pycollada-0.7.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656396943
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pycollada
cp %{_builddir}/pycollada-0.7.2/COPYING %{buildroot}/usr/share/package-licenses/pypi-pycollada/865bc093426b2af2846b32a0789fa7b4daa8b519
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pycollada/865bc093426b2af2846b32a0789fa7b4daa8b519

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
